---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10003
mongodb:
  host: ns-ns-mongodb
  port: 27017
  username: nsuser
  password: nsuser
  auth_db: notes_system
  database: notes_system
  collection: notes